name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Save service account key to file
      - name: Write Service Account Key
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/firebase-service-account.json

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting:your-site-name
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json
